# Generated by Django 5.1.1 on 2024-09-09 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_boleta', models.CharField(max_length=255, unique=True)),
                ('carrera', models.CharField(choices=[('ISC', 'sistemas_computacionales'), ('LCD', 'licencia_datos'), ('IIA', 'inteligencia_artificial')], default='ISC', max_length=3)),
                ('plan', models.CharField(max_length=50)),
                ('nombre_protocolo', models.CharField(max_length=50)),
                ('es_alumno', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['num_boleta'],
                'indexes': [models.Index(fields=['num_boleta'], name='usuarios_al_num_bol_629fe3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=255, unique=True)),
                ('materias', models.CharField(max_length=255)),
                ('es_profesor', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['matricula'],
                'indexes': [models.Index(fields=['matricula'], name='usuarios_pr_matricu_0e1d73_idx')],
            },
        ),
    ]
